export default [
  { name: 'chakra', dsd: 'chakra-factory', chakra: '/website/pages/docs/features/chakra-factory.mdx' },
  { name: 'Button', dsd: 'button', chakra: '/website/pages/docs/form/button.mdx' },
  { name: 'Checkbox', dsd: 'checkbox', chakra: '/website/pages/docs/form/checkbox.mdx' },
  { name: 'Editable', dsd: 'editable', chakra: '/website/pages/docs/form/editable.mdx' },
  { name: 'FormControl', dsd: 'form-control', chakra: '/website/pages/docs/form/form-control.mdx' },
  { name: 'IconButton', dsd: 'icon-button', chakra: '/website/pages/docs/form/icon-button.mdx' },
  { name: 'Input', dsd: 'input', chakra: '/website/pages/docs/form/input.mdx' },
  { name: 'NumberInput', dsd: 'number-input', chakra: '/website/pages/docs/form/number-input.mdx' },
  { name: 'PinInput', dsd: 'pin-input', chakra: '/website/pages/docs/form/pin-input.mdx' },
  { name: 'Radio', dsd: 'radio', chakra: '/website/pages/docs/form/radio.mdx' },
  { name: 'Select', dsd: 'select', chakra: '/website/pages/docs/form/select.mdx' },
  { name: 'Slider', dsd: 'slider', chakra: '/website/pages/docs/form/slider.mdx' },
  { name: 'Switch', dsd: 'switch', chakra: '/website/pages/docs/form/switch.mdx' },
  { name: 'TextArea', dsd: 'textarea', chakra: '/website/pages/docs/form/textarea.mdx' },

  { name: 'Badge', dsd: 'badge', chakra: '/website/pages/docs/data-display/badge.mdx' },
  { name: 'Code', dsd: 'code', chakra: '/website/pages/docs/data-display/code.mdx' },
  { name: 'Divider', dsd: 'divider', chakra: '/website/pages/docs/data-display/divider.mdx' },
  { name: 'Kbd', dsd: 'kbd', chakra: '/website/pages/docs/data-display/kbd.mdx' },
  { name: 'List', dsd: 'list', chakra: '/website/pages/docs/data-display/list.mdx' },
  { name: 'Stat', dsd: 'stat', chakra: '/website/pages/docs/data-display/stat.mdx' },
  { name: 'Table', dsd: 'table', chakra: '/website/pages/docs/data-display/table.mdx' },
  { name: 'Tag', dsd: 'tag', chakra: '/website/pages/docs/data-display/tag.mdx' },

  { name: 'Alert', dsd: 'alert', chakra: '/website/pages/docs/feedback/alert.mdx' },
  { name: 'CircularProgress', dsd: 'circular-progress', chakra: '/website/pages/docs/feedback/circular-progress.mdx' },
  { name: 'Progress', dsd: 'progress', chakra: '/website/pages/docs/feedback/progress.mdx' },
  { name: 'Skeleton', dsd: 'skeleton', chakra: '/website/pages/docs/feedback/skeleton.mdx' },
  { name: 'Spinner', dsd: 'spinner', chakra: '/website/pages/docs/feedback/spinner.mdx' },
  { name: 'Toast', dsd: 'toast', chakra: '/website/pages/docs/feedback/toast.mdx' },

  { name: 'AspectRatio', dsd: 'aspect-ratio', chakra: '/website/pages/docs/layout/aspect-ratio.mdx' },
  { name: 'Box', dsd: 'box', chakra: '/website/pages/docs/layout/box.mdx' },
  { name: 'Center', dsd: 'center', chakra: '/website/pages/docs/layout/center.mdx' },
  { name: 'Container', dsd: 'container', chakra: '/website/pages/docs/layout/container.mdx' },
  { name: 'Flex', dsd: 'flex', chakra: '/website/pages/docs/layout/flex.mdx' },
  { name: 'Grid', dsd: 'grid', chakra: '/website/pages/docs/layout/grid.mdx' },
  { name: 'SimpleGrid', dsd: 'simple-grid', chakra: '/website/pages/docs/layout/simple-grid.mdx' },
  { name: 'Stack', dsd: 'stack', chakra: '/website/pages/docs/layout/stack.mdx' },
  { name: 'Wrap', dsd: 'wrap', chakra: '/website/pages/docs/layout/wrap.mdx' },

  { name: 'Avatar', dsd: 'avatar', chakra: '/website/pages/docs/media-and-icons/avatar.mdx' },
  { name: 'Icon', dsd: 'icon', chakra: '/website/pages/docs/media-and-icons/icon.mdx' },
  { name: 'Image', dsd: 'image', chakra: '/website/pages/docs/media-and-icons/image.mdx' },

  { name: 'Breadcrumb', dsd: 'breadcrumb', chakra: '/website/pages/docs/navigation/breadcrumb.mdx' },
  { name: 'Link', dsd: 'link', chakra: '/website/pages/docs/navigation/link.mdx' },
  { name: 'LinkOverlay', dsd: 'link-overlay', chakra: '/website/pages/docs/navigation/link-overlay.mdx' },

  { name: 'Accordion', dsd: 'accordion', chakra: '/website/pages/docs/disclosure/accordion.mdx' },
  { name: 'Tabs', dsd: 'tabs', chakra: '/website/pages/docs/disclosure/tabs.mdx' },
  { name: 'VisuallyHidden', dsd: 'visually-hidden', chakra: '/website/pages/docs/disclosure/visually-hidden.mdx' },

  { name: 'AlertDialog', dsd: 'alert-dialog', chakra: '/website/pages/docs/overlay/alert-dialog.mdx' },
  { name: 'Drawer', dsd: 'drawer', chakra: '/website/pages/docs/overlay/drawer.mdx' },
  { name: 'Menu', dsd: 'menu', chakra: '/website/pages/docs/overlay/menu.mdx' },
  { name: 'Modal', dsd: 'modal', chakra: '/website/pages/docs/overlay/modal.mdx' },
  { name: 'Popover', dsd: 'popover', chakra: '/website/pages/docs/overlay/popover.mdx' },
  { name: 'Tooltip', dsd: 'tooltip', chakra: '/website/pages/docs/overlay/tooltip.mdx' },
];